apiVersion: secrets.phase.dev/v1alpha1
kind: PhaseSecret
metadata:
  name: example-phase-secret
  namespace: default
spec:
  phaseAppEnv: "prod" # OPTIONAL - The Phase application environment to fetch secrets from
  phaseHost: "https://console.phase.dev" # OPTIONAL - URL of a Phase Console instance
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: "phase-service-token" # Name of the Phase service token with access to your application
        secretNamespace: "default"
  managedSecretReferences: # Managed secrets in Kubernetes that Phase will sync secrets with
    - secretName: "my-application-secret" # Name of the managed secret in Kubernetes that will be consumed by your application 
      secretNamespace: "default"
