apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phase.fullname" . }}-frontend
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "phase.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "phase.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: {{ include "phase.fullname" . }}-config
        - secretRef:
            name: {{ include "phase.fullname" . }}-secrets
        env:
        - name: NEXTAUTH_URL
          value: "$(HTTP_PROTOCOL)$(HOST)"
        - name: BACKEND_API_BASE
          value: "$(HTTP_PROTOCOL)$(HOST)/service"
        - name: NEXT_PUBLIC_BACKEND_API_BASE
          value: "$(HTTP_PROTOCOL)$(HOST)/service"
        - name: NEXT_PUBLIC_NEXTAUTH_PROVIDERS
          value: "$(SSO_PROVIDERS)"
        {{- if .Values.frontend.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
        {{- end }}