name: Build and Push Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag

      - name: Build and push (PR)
        if: github.event_name == 'pull_request'
        run: |
          SHORT_SHA=$(git rev-parse --verify HEAD | cut -c 1-7)
          docker build -t phasehq/kubernetes-operator:${SHORT_SHA} .
          docker push phasehq/kubernetes-operator:${SHORT_SHA}

      - name: Build and push (Main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t phasehq/kubernetes-operator:latest .
          docker push phasehq/kubernetes-operator:latest

      - name: Build and push (Release tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build -t phasehq/kubernetes-operator:${{ steps.extract_tag.outputs.tag }} .
          docker push phasehq/kubernetes-operator:${{ steps.extract_tag.outputs.tag }}
